# Generated by Django 3.2 on 2023-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230830_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
