# Generated by Django 3.2 on 2023-09-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230831_0802'),
        ('reviews', '0008_alter_title_category'),
    ]

    operations = [
    ]
