# Generated by Django 3.2 on 2023-09-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_merge_20230901_1114'),
        ('reviews', '0009_merge_20230901_1422'),
    ]

    operations = [
    ]
