# Generated by Django 3.2 on 2023-09-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20230901_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
