# Generated by Django 3.2 on 2023-09-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20230902_1305'),
        ('reviews', '0011_auto_20230902_1830'),
    ]

    operations = [
    ]
