# Generated by Django 3.2 on 2023-09-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_merge_0011_auto_20230902_1305_0011_auto_20230902_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreTitle',
            new_name='TitleGenre',
        ),
    ]
